### ISSUE TITLE
Sanitize user when creating credentials

### ISSUE THREAD

**Issue by panlinux** [CanonicalLtd/basic-auth-service#1]
We should probably prevent funny characters in the the user string when creating a set of credentials, since that ends up directly in the URL for some API calls:
```
$ dev/api-client --creds api-user:eX8uspKWUS5UYY5t8lYp credentials add user=../andreas
201 Created - {'token': 'mf2z9BtCa7U8IAIETRAK:72bO4kxi1Knezc4ZWLVY', 'user': '../andreas'}
```

```
basic-auth=> select * from credentials;
 id |    user    |       username       |       password       
----+------------+----------------------+----------------------
  1 | ../andreas | mf2z9BtCa7U8IAIETRAK | 72bO4kxi1Knezc4ZWLVY
(1 row)
```

Server log when trying to delete this user:
`127.0.0.1 - - [22/May/2017:20:51:50 +0000] "DELETE /api/credentials/../andreas HTTP/1.1" 404 172 "-" "python-requests/2.9.1"`

**Comment by albertodonato** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Sanitize user credentials](https://trello.com/c/AGMxqKDe/37-sanitize-user-credentials)

**Comment by albertodonato** [comment]
Fixed on the client side.
This was a missing url encoding of the resource id (which should have become `..%2Fandreas` in that case) in the client, which makes it request the wrong url.
